# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

EDITORCONFIG_FILTER_REGEX_EXCLUDE: '(mvnw|mvnw.cmd|LICENSE)'

DISABLE_LINTERS:
  - SPELL_CSPELL

SARIF_REPORTER: true
